---
version: "1.4.10-7"
enable-multiworld-chat: false
# Please check if you have all PurePerms groups in your server here
# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset
# Available PureChat tags
# {display_name} Get the player's username.
# {msg} Get the player's message.
# {prefix} Get PurePerms Prefix of the rank.
# {suffix} Get the PurePerms Suffix of the rank.
# {world} Get the PurePerms world the player is in.
groups:
  Guest:
    chat: '&7[&6{prefix}&7] &7[&eGuest&7] &7[{display_name}] > {msg}'
    nametag: ''
    worlds: []
...
